server:
  port: 9191

spring:
  application:
    name: api-gateway
  
  cloud:
    discovery:
      enabled: true
    gateway:
      mvc:
        routes:
        - id: department-service
          uri: lb://department-service
          predicates:
          - Path=/department/**
        - id: user-service
          uri: lb://user-service
          predicates:
          - Path=/user/**

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}